# Generated by Django 6.0.2 on 2026-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('sys_admin', 'System Admin')], default='user', max_length=10),
        ),
    ]
