# Generated by Django 6.0.2 on 2026-03-16 17:49

from django.db import migrations, models


def migrate_details_to_metadata(apps, schema_editor):
    ActivityLog = apps.get_model('core', 'ActivityLog')
    for log in ActivityLog.objects.all().iterator():
        metadata = dict(log.metadata or {})
        if log.details:
            metadata.setdefault('legacy_details', log.details)
        log.metadata = metadata
        log.save(update_fields=['metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(migrate_details_to_metadata, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
    ]
