# Generated by Django 6.0.2 on 2026-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='close_time',
            field=models.TimeField(default='20:00', help_text='Time the facility closes.'),
        ),
        migrations.AddField(
            model_name='facility',
            name='open_time',
            field=models.TimeField(default='08:00', help_text='Time the facility opens.'),
        ),
    ]
