# Generated by Django 6.0.2 on 2026-03-16 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_managers(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    UserProfile = apps.get_model('users', 'UserProfile')

    admin_profile = UserProfile.objects.filter(role='admin').order_by('id').first()
    if admin_profile:
        Facility.objects.filter(manager__isnull=True).update(manager_id=admin_profile.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
        ('facilities', '0002_facility_close_time_facility_open_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='manager',
            field=models.ForeignKey(
                blank=True,
                help_text='Only the assigned manager can approve or reject bookings for this facility.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_facilities',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='facility',
            name='max_pending_requests',
            field=models.IntegerField(default=3),
        ),
        migrations.RunPython(assign_existing_managers, migrations.RunPython.noop),
    ]
