# Generated by Django 6.0.2 on 2026-03-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_production_architecture'),
        ('users', '0003_department_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. projector,AC,whiteboard', max_length=300),
        ),
        migrations.AddField(
            model_name='facility',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department that owns / administers this facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='users.department'),
        ),
    ]
