# Generated by Django 6.0.2 on 2026-03-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_amenities_facility_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Assigned managers who can approve or reject bookings for this facility.', related_name='managed_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Only the assigned manager can approve or reject bookings for this facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_managed_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
