# Generated by Django 6.0.2 on 2026-03-21 14:41

from django.db import migrations


def copy_managers(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    for facility in Facility.objects.all():
        if facility.manager_id:
            facility.managers.add(facility.manager_id)

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_managers_alter_facility_manager'),
    ]

    operations = [
        migrations.RunPython(copy_managers, reverse_copy),
    ]
