# Generated by Django 6.0.2 on 2026-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_auto_20260321_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='manager',
        ),
    ]
