# Generated by Django 6.0.2 on 2026-03-16 17:49

from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def populate_booking_datetimes_and_policies(apps, schema_editor):
    BookingRequest = apps.get_model('bookings', 'BookingRequest')
    BookingPolicy = apps.get_model('bookings', 'BookingPolicy')
    Facility = apps.get_model('facilities', 'Facility')

    current_timezone = timezone.get_current_timezone()
    for booking in BookingRequest.objects.all().iterator():
        booking.start_datetime = timezone.make_aware(
            datetime.combine(booking.date, booking.start_time),
            current_timezone,
        )
        booking.end_datetime = timezone.make_aware(
            datetime.combine(booking.date, booking.end_time),
            current_timezone,
        )
        booking.save(update_fields=['start_datetime', 'end_datetime'])

    for facility in Facility.objects.all().iterator():
        BookingPolicy.objects.get_or_create(facility_id=facility.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_production_architecture'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_duration_hours', models.PositiveIntegerField(default=4)),
                ('max_advance_days', models.PositiveIntegerField(default=30)),
                ('max_bookings_per_user', models.PositiveIntegerField(default=3)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policy', to='facilities.facility')),
            ],
            options={
                'ordering': ['facility__name'],
            },
        ),
        migrations.RunPython(populate_booking_datetimes_and_policies, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='start_time',
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['facility', 'status', 'start_datetime'], name='bookings_bo_facilit_a75914_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['facility', 'status', 'end_datetime'], name='bookings_bo_facilit_8c1f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['user', 'status', 'start_datetime'], name='bookings_bo_user_id_e262e3_idx'),
        ),
    ]
