# Generated by Django 6.0.2 on 2026-03-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpolicy_required_approval_levels_approvalstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('until_date', models.DateField()),
                ('max_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rule', to='bookings.bookingrequest')),
            ],
        ),
    ]
